### ISSUE TITLE
combine variable declaration and definition

### ISSUE THREAD

**Issue by incredibleLeitman** [asharif123/TileCalculator#1]
https://github.com/asharif123/TileCalculator/blob/a8c7a5c78f4f4e4a9dddb1297301ae682e50a018/TileCalculator/Program.cs#L10
https://github.com/asharif123/TileCalculator/blob/a8c7a5c78f4f4e4a9dddb1297301ae682e50a018/TileCalculator/Program.cs#L15

In C# you don't have to declare all the variables that you are using on top: usually it is more readable to just create them where you need em and directly assign a value:
```c#
string width = Console.ReadLine();
```

**Comment by asharif123** [comment]
fixed issue number #1 where I combined variable as one line instead of 2 separate lines
