### ISSUE TITLE
Define constants for your magic numbers

### ISSUE THREAD

**Issue by mayisa87** [asharif123/TileCalculator#2]
https://github.com/asharif123/TileCalculator/blob/a4b2334b5b40ddf64f8645832aeccb42306147a6/TileCalculator/Program.cs#L52

The values 20 and 86 should be defined as constants. See this video again: https://course.raketementoring.com/courses/rakete-mentoring/lectures/46714297

**Comment by asharif123** [comment]
updated variables names whose values don't change by adding const in front

**Comment by mayisa87** [comment]
[18:08, 27.10.2023] Isabella Mayer: Concerning your try to introduce constants. This is not exactly how it should be done. I'll reopen the issue therefore.

You should have for each number/value one constant. And constants are always named in UPPERCASE letters like:
const float double FLOORING_PER_HOUR = 20.00;
[18:09, 27.10.2023] Isabella Mayer: Constants are always defined first of all at the beginning of the Main function. All of them :)

**Comment by asharif123** [comment]
updated variable names to be capitalized and assigned each variable name separately to flooring per hour and flooring labor values
