### ISSUE TITLE
Disable nullable warnings

### ISSUE THREAD

**Issue by mayisa87** [asharif123/TileCalculator#3]
https://github.com/asharif123/TileCalculator/blob/a4b2334b5b40ddf64f8645832aeccb42306147a6/TileCalculator/TileCalculator.csproj#L7

Please have a look to this video and change your settings :) 
https://course.raketementoring.com/courses/rakete-mentoring/lectures/45560433

**Comment by asharif123** [comment]
updated code to get rid of warning messages
