### ISSUE TITLE
Do Calculations step by step

### ISSUE THREAD

**Issue by mayisa87** [asharif123/TileCalculator#4]
https://github.com/asharif123/TileCalculator/blob/a4b2334b5b40ddf64f8645832aeccb42306147a6/TileCalculator/Program.cs#L50

Do not calculate all at once. Better first calculate the area for the shape, and store it into a separate variable "area" for example.
Then use this area variable in your calculation for the tile total costs.

**Comment by asharif123** [comment]
Updated variable names to separately calculate areas for rectangle and triangle.
