### ISSUE TITLE
Get rid of duplicated code

### ISSUE THREAD

**Issue by mayisa87** [asharif123/TileCalculator#5]
As already mentioned in WA, one of the most important lessons to learn now at the beginning is, to get rid of duplicated code and how to use and reuse your variables.

Please rewatch the videos about visibility below!!

The goal in all code is, to have no duplicated code or as less as possible. So everything that is the same for rectangle and triangle, should be done outside of your if blocks. You already do it right for example by letting the user enter the cost per unit before the if. The same you could to for the cost calculation. Instead of calculating the same stuff twice in each if block, you could move it out of the if, for example after your if blocks.

Why and what for? Imagine you would have several shape types not only two, and you would need to extend your logic or calculations. That would mean that you need to change each single if block and the code in it. Even if you want to only change the output message. Believe me you would for sure oversee something and therefore always try to have only one single source of truth.

Here again what messages from Whats App.

**Visibility of variables:**
So next step is, to define variables that can be used for all shape types. 
Like instead of having rectangleTileTotal and triagnleTileTotal you define/declare a variable tileTotal

This variable you need to declare for example **before** your if, and reuse it in your if blocks.
If you need more details on the visibility of variables, you can see this loom I made: https://www.loom.com/share/71d95e3dd33347ecb9cee14715a6f782

**Concerning re-usage of variables:**
Maybe one addtional thing to mention, as it is important to understand at the beginning. 
If you for example have a variable and use a formula to calculate something like the area of a rectangle, let's say, length = 3, width =4
double area = length*width;

What will happen is, that the variable area is set to the value 12.

If you later in code change length to 5 and width to 6, your variable area is not affected. To again update the area value you would need to write again:
area = length*width;

So that's why it doesn't matter, that you use in one if a different formula than in the other. There is no relation between formula and variable. A variable just receives the value that you set to it. There is no relation and no automatic update of varibles

**Comment by asharif123** [comment]
fix issue #5 got rid of duplicated code

**Comment by asharif123** [comment]
fixed issue #5 got rid of duplicated code
