### ISSUE TITLE
remove unused usings

### ISSUE THREAD

**Issue by incredibleLeitman** [asharif123/TileCalculator#6]
https://github.com/asharif123/TileCalculator/blob/2045678e065787644a6b2368e234a6db39190ed0/TileCalculator/Program.cs#L11

Do you really need this using?
You should regularly (and before each commit 👆 ) resolve those by either using the shortcut (default Ctrl+R, Ctrl+G on windows) or right click in the usings block and select "Remove and Sort usings"

**Comment by asharif123** [comment]
fixed issue #6 removing unused usings

**Comment by asharif123** [comment]
fixed issue https://github.com/asharif123/TileCalculator/issues/6 removing unused usings
