### ISSUE TITLE
declare floating point variables with a dot

### ISSUE THREAD

**Issue by incredibleLeitman** [asharif123/TileCalculator#7]
https://github.com/asharif123/TileCalculator/blob/2045678e065787644a6b2368e234a6db39190ed0/TileCalculator/Program.cs#L22-L26

if you use float values write them with a dot and append an "F" to make it more visible that it is a floating point value:
```cs
const float FLOORING_SQUARE_FEET = 20.0F; 
const float FLOORING_PER_HOUR = 85.0F; 
```

**Comment by asharif123** [comment]
fixed issue #7 by adding dot and appending F to floating point variables
